import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans:    ['Inter', 'system-ui', 'sans-serif'],
        display: ['Syne', 'system-ui', 'sans-serif'],
        mono:    ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        '2xs': ['10px', '14px'],
        xs:    ['11px', '15px'],
        sm:    ['12px', '17px'],
        base:  ['13px', '19px'],
        md:    ['14px', '20px'],
        lg:    ['16px', '24px'],
        xl:    ['20px', '28px'],
        '2xl': ['24px', '30px'],
        '3xl': ['30px', '36px'],
      },
      letterSpacing: {
        tighter: '-0.6px',
        tight:   '-0.4px',
        snug:    '-0.2px',
        wide:    '0.3px',
        wider:   '0.6px',
        widest:  '0.9px',
      },
      colors: {
        brand: {
          50:  '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#1e1b4b',
        },
        surface: {
          DEFAULT: '#ffffff',
          muted:   '#f8fafc',
          subtle:  '#f1f5f9',
          overlay: '#e2e8f0',
        },
        sidebar: {
          DEFAULT:      '#0f172a',
          hover:        'rgba(255,255,255,0.05)',
          active:       'rgba(99,102,241,0.14)',
          border:       'rgba(255,255,255,0.06)',
          text:         'rgba(248,250,252,0.45)',
          'text-active': '#a5b4fc',
        },
        status: {
          'paid-bg':           '#dcfce7',
          'paid-text':         '#166534',
          'paid-border':       '#bbf7d0',
          'pending-bg':        '#fef3c7',
          'pending-text':      '#92400e',
          'pending-border':    '#fde68a',
          'overdue-bg':        '#fee2e2',
          'overdue-text':      '#991b1b',
          'overdue-border':    '#fecaca',
          'overdue-row':       '#fff5f5',
          'active-bg':         '#dbeafe',
          'active-text':       '#1e40af',
          'vacant-bg':         '#fee2e2',
          'vacant-text':       '#991b1b',
          'occupied-bg':       '#dcfce7',
          'occupied-text':     '#166534',
          'maintenance-bg':    '#fef3c7',
          'maintenance-text':  '#92400e',
          'expiring-bg':       '#fef3c7',
          'expiring-text':     '#92400e',
          'expired-bg':        '#f1f5f9',
          'expired-text':      '#64748b',
          'submitted-bg':      '#f1f5f9',
          'submitted-text':    '#475569',
          'assigned-bg':       '#dbeafe',
          'assigned-text':     '#1e40af',
          'in-progress-bg':    '#fef3c7',
          'in-progress-text':  '#92400e',
          'completed-bg':      '#dcfce7',
          'completed-text':    '#166534',
          'cancelled-bg':      '#f1f5f9',
          'cancelled-text':    '#64748b',
        },
      },
      borderRadius: {
        sm:    '4px',
        md:    '6px',
        DEFAULT: '8px',
        lg:    '10px',
        xl:    '14px',
        '2xl': '18px',
        pill:  '9999px',
      },
      borderWidth: {
        DEFAULT: '0.5px',
        thin:    '0.5px',
        base:    '1px',
      },
      boxShadow: {
        card:        '0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)',
        'card-hover':'0 4px 12px rgba(0,0,0,0.08), 0 2px 4px rgba(0,0,0,0.04)',
        focus:       '0 0 0 3px rgba(99,102,241,0.25)',
        none:        'none',
      },
    },
  },
  plugins: [],
} satisfies Config;
